In [137]:
import pandas as pd
import datetime as dt

In [138]:
csv_path = "Resources/202209-citibike-tripdata.csv"
bike = pd.read_csv(csv_path)
bike.head()

/var/folders/r3/ljt9syw176jcr74xd342l8r40000gn/T/ipykernel_16005/470208310.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.read_csv(csv_path)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,42B9E1161E021F66,classic_bike,2022-09-17 16:06:45,2022-09-17 16:18:03,Henry St & Degraw St,4380.08,7 Ave & Park Pl,4125.07,40.684736,-73.999088,40.677615,-73.973243,member
1,FE5FB109CA0FB68B,classic_bike,2022-09-25 14:26:25,2022-09-25 14:39:43,6 Ave & W 34 St,6364.1,W 50 St & 9 Ave,6854.05,40.749640,-73.988050,40.763605,-73.989180,member
2,D4E9E27DCE9CC556,classic_bike,2022-09-15 13:25:37,2022-09-15 13:51:35,6 Ave & W 34 St,6364.1,5 Ave & E 78 St,7161.08,40.749640,-73.988050,40.776321,-73.964274,member
3,757BFFFB009E8D21,classic_bike,2022-09-16 18:46:33,2022-09-16 18:52:42,48 St & 5 Ave,3202.06,36 St & 4 Ave,3420.01,40.646351,-74.009271,40.654144,-74.004220,member
4,4E6360AD2986736E,classic_bike,2022-09-10 09:20:56,2022-09-10 09:30:20,Steinway St & Ditmars Blvd,7074.01,Crescent St & 30 Ave,6958.06,40.772621,-73.906240,40.768692,-73.924957,member

In [139]:
#bike.dtypes

In [140]:
bike['started_at']=bike['started_at'].astype("datetime64")
bike['ended_at']=bike['ended_at'].astype("datetime64")

In [141]:
#bike.dtypes

In [142]:
tripduration=(bike['ended_at']-bike['started_at']).dt

tripduration=tripduration.seconds

tripduration.head()

0     678
1     798
2    1558
3     369
4     564
dtype: int64

In [143]:
bike.insert(loc=4,
          column='trip_duration',
          value=tripduration)
bike.head()

,ride_id,rideable_type,started_at,ended_at,trip_duration,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,42B9E1161E021F66,classic_bike,2022-09-17 16:06:45,2022-09-17 16:18:03,678,Henry St & Degraw St,4380.08,7 Ave & Park Pl,4125.07,40.684736,-73.999088,40.677615,-73.973243,member
1,FE5FB109CA0FB68B,classic_bike,2022-09-25 14:26:25,2022-09-25 14:39:43,798,6 Ave & W 34 St,6364.1,W 50 St & 9 Ave,6854.05,40.749640,-73.988050,40.763605,-73.989180,member
2,D4E9E27DCE9CC556,classic_bike,2022-09-15 13:25:37,2022-09-15 13:51:35,1558,6 Ave & W 34 St,6364.1,5 Ave & E 78 St,7161.08,40.749640,-73.988050,40.776321,-73.964274,member
3,757BFFFB009E8D21,classic_bike,2022-09-16 18:46:33,2022-09-16 18:52:42,369,48 St & 5 Ave,3202.06,36 St & 4 Ave,3420.01,40.646351,-74.009271,40.654144,-74.004220,member
4,4E6360AD2986736E,classic_bike,2022-09-10 09:20:56,2022-09-10 09:30:20,564,Steinway St & Ditmars Blvd,7074.01,Crescent St & 30 Ave,6958.06,40.772621,-73.906240,40.768692,-73.924957,member

In [144]:
bike1 = bike[(bike['started_at'] > "2022-09-27")]
bike1

,ride_id,rideable_type,started_at,ended_at,trip_duration,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
9,C5C47628ABCB1528,electric_bike,2022-09-27 08:30:28,2022-09-27 08:46:11,943,Graham Ave & Herbert St,5403.05,Forsyth St & Broome St,5453.05,40.719293,-73.945004,40.718939,-73.992663,member
16,68C3CA9D63E06C5D,classic_bike,2022-09-28 18:05:34,2022-09-28 18:12:27,413,Cleveland Pl & Spring St,5492.05,E 11 St & 3 Ave,5788.16,40.722104,-73.997249,40.731270,-73.988490,member
17,B0CD12313A602FC9,classic_bike,2022-09-29 11:18:12,2022-09-29 11:25:28,436,4 Ave & 3 St,4028.04,Hanson Pl & Ashland Pl,4395.07,40.673746,-73.985649,40.685068,-73.977908,member
19,E5474A01A21EF842,classic_bike,2022-09-27 12:39:56,2022-09-27 12:47:29,453,4 Ave & 3 St,4028.04,Hanson Pl & Ashland Pl,4395.07,40.673746,-73.985649,40.685068,-73.977908,member
35,4F7D0F34008B19CF,classic_bike,2022-09-29 20:47:08,2022-09-29 22:16:47,5379,Fulton St & Adams St,4637.06,NaN,NaN,40.692500,-73.989602,40.670000,-73.990000,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3507098,385C391A18BFD49E,classic_bike,2022-09-29 15:57:00,2022-09-29 16:01:42,282,E 10 St & 2 Ave,5746.02,E 22 St & 2 Ave,5971.09,40.729708,-73.986598,40.737169,-73.981225,member
3507106,EEF2E04D20191661,classic_bike,2022-09-30 14:06:40,2022-09-30 14:25:19,1119,Columbus Ave & W 72 St,7175.05,Broadway & W 155 St,8123.02,40.777244,-73.978896,40.832990,-73.945920,member
3507108,7A5BDD970BAAD824,electric_bike,2022-09-28 19:47:38,2022-09-28 20:05:55,1097,Ashland Pl & Dekalb Ave,4513.09,1 Ave & E 6 St,5626.15,40.690065,-73.978776,40.726331,-73.986169,member
3507111,46D67A985602CF1E,classic_bike,2022-09-27 13:08:06,2022-09-27 13:18:44,638,Greenwich St & Perry St,5922.04,Lafayette St & E 8 St,5788.13,40.740573,-74.005349,40.730207,-73.991026,member
3507112,9905EDB31405A583,classic_bike,2022-09-27 13:07:03,2022-09-27 13:28:03,1260,Columbus Ave & W 72 St,7175.05,E 39 St & Lexington Ave,6389.09,40.777057,-73.978985,40.749499,-73.977292,member

In [145]:
bike1.to_csv('Resources/202209-citibike.csv',index=False)

In [147]:
bike3= bike[(bike['started_at'] > "2022-09-24")]
bike3.sort_values('started_at')

,ride_id,rideable_type,started_at,ended_at,trip_duration,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
1144106,C3F644975119BEB4,classic_bike,2022-09-24 00:00:01,2022-09-24 00:09:56,595,5 Ave & E 93 St,7372.1,Columbus Ave & W 95 St,7520.07,40.785973,-73.957523,40.791956,-73.968087,member
582493,6456CF4791A42EDA,electric_bike,2022-09-24 00:00:04,2022-09-24 00:07:48,464,S 4 St & Wythe Ave,5204.05,Carlton Ave & Flushing Ave,4732.08,40.712859,-73.965903,40.697787,-73.973736,member
1736159,B989C2D32E82F927,classic_bike,2022-09-24 00:00:11,2022-09-24 00:04:47,276,Union Ave & Jackson St,5300.06,N 6 St & Bedford Ave,5379.10,40.716075,-73.952029,40.717452,-73.958509,member
451708,5F86CD00B0507C1C,classic_bike,2022-09-24 00:00:14,2022-09-24 00:11:28,674,E 5 St & Ave A,5626.06,Thompson St & Bleecker St,5721.07,40.724790,-73.984301,40.728401,-73.999688,member
3336423,C16CB056B5D228C4,classic_bike,2022-09-24 00:00:15,2022-09-24 00:07:14,419,Mott St & Prince St,5561.04,W Broadway & W Houston St,5644.05,40.723180,-73.994800,40.726378,-74.000472,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1665150,E51BA22B85BDF14E,classic_bike,2022-09-30 23:59:55,2022-10-01 00:14:11,856,W 11 St & 6 Ave,5914.03,W 45 St & 8 Ave,6676.02,40.735324,-73.998004,40.759291,-73.988597,casual
2184532,A4CA64A8AE032576,classic_bike,2022-09-30 23:59:56,2022-10-01 00:00:43,47,3 Ave & E 170 St,8137.06,E 171 St & 3 Ave,8171.06,40.834987,-73.903722,40.837119,-73.902185,member
2145568,38C35EAAC48B953F,classic_bike,2022-09-30 23:59:57,2022-10-01 00:02:24,147,W 44 St & 11 Ave,6756.05,W 43 St & 10 Ave,6756.01,40.762009,-73.996975,40.760094,-73.994618,member
375172,AAE0C6C73B8410D6,classic_bike,2022-09-30 23:59:57,2022-10-01 00:02:04,127,7 Ave & 41 St,3192.05,5 Ave & 41 St,3306.03,40.647379,-74.000911,40.649983,-74.005144,member
2147180,5E3240061B00264E,classic_bike,2022-09-30 23:59:59,2022-10-01 00:13:26,807,Greene Ave & Throop Ave,4510.04,Carroll St & Washington Ave,3887.03,40.689529,-73.942097,40.668674,-73.961815,member

In [148]:
bike3.to_csv('Resources/202209-7daysCitibike.csv',index=False)

In [92]:
csv_path2 = "Resources/202109-citibike-tripdata.csv"
bike2 = pd.read_csv(csv_path2)
bike2.head()

/var/folders/r3/ljt9syw176jcr74xd342l8r40000gn/T/ipykernel_16005/1772281152.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike2 = pd.read_csv(csv_path2)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A789BD2808767C24,classic_bike,2021-09-16 12:34:39,2021-09-16 12:36:05,Clinton St\t& Cherry St,5190.09,Madison St & Clinton St,5190.07,40.711471,-73.986726,40.712690,-73.987763,member
1,B3E45CE415FDF1E7,classic_bike,2021-09-28 20:36:25,2021-09-28 20:37:58,Clinton St & Grand St,5303.06,Madison St & Clinton St,5190.07,40.715595,-73.987030,40.712690,-73.987763,member
2,50433A2E1F35CBBB,classic_bike,2021-09-26 20:08:43,2021-09-26 20:25:36,LaGuardia Pl & W 3 St,5721.14,Greenwich Ave & Charles St,5914.08,40.729170,-73.998102,40.735238,-74.000271,casual
3,C478A0B3E61B504F,electric_bike,2021-09-06 18:25:20,2021-09-06 18:30:21,LaGuardia Pl & W 3 St,5721.14,Greenwich Ave & Charles St,5914.08,40.729170,-73.998102,40.735238,-74.000271,casual
4,2B82A80EECFC4458,electric_bike,2021-09-07 18:39:08,2021-09-07 18:54:03,E 65 St & 2 Ave,6860.12,28 St & 41 Ave,6462.19,40.764719,-73.962221,40.751047,-73.937970,casual

In [93]:
bike2['started_at']=bike2['started_at'].astype("datetime64")
bike2['ended_at']=bike2['ended_at'].astype("datetime64")

In [94]:
tripduration2=(bike2['ended_at']-bike2['started_at']).dt

tripduration2=tripduration2.seconds

tripduration2.head()

0      86
1      93
2    1013
3     301
4     895
dtype: int64

In [95]:
bike2.insert(loc=4,
          column='trip_duration',
          value=tripduration2)
bike2.head()

,ride_id,rideable_type,started_at,ended_at,trip_duration,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A789BD2808767C24,classic_bike,2021-09-16 12:34:39,2021-09-16 12:36:05,86,Clinton St\t& Cherry St,5190.09,Madison St & Clinton St,5190.07,40.711471,-73.986726,40.712690,-73.987763,member
1,B3E45CE415FDF1E7,classic_bike,2021-09-28 20:36:25,2021-09-28 20:37:58,93,Clinton St & Grand St,5303.06,Madison St & Clinton St,5190.07,40.715595,-73.987030,40.712690,-73.987763,member
2,50433A2E1F35CBBB,classic_bike,2021-09-26 20:08:43,2021-09-26 20:25:36,1013,LaGuardia Pl & W 3 St,5721.14,Greenwich Ave & Charles St,5914.08,40.729170,-73.998102,40.735238,-74.000271,casual
3,C478A0B3E61B504F,electric_bike,2021-09-06 18:25:20,2021-09-06 18:30:21,301,LaGuardia Pl & W 3 St,5721.14,Greenwich Ave & Charles St,5914.08,40.729170,-73.998102,40.735238,-74.000271,casual
4,2B82A80EECFC4458,electric_bike,2021-09-07 18:39:08,2021-09-07 18:54:03,895,E 65 St & 2 Ave,6860.12,28 St & 41 Ave,6462.19,40.764719,-73.962221,40.751047,-73.937970,casual

In [108]:
bike2 = bike2[(bike2['started_at'] > "2021-09-27")]
bike2

,ride_id,rideable_type,started_at,ended_at,trip_duration,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
1,B3E45CE415FDF1E7,classic_bike,2021-09-28 20:36:25,2021-09-28 20:37:58,93,Clinton St & Grand St,5303.06,Madison St & Clinton St,5190.07,40.715595,-73.987030,40.712690,-73.987763,member
5,2EA14B066F3794E1,electric_bike,2021-09-27 13:41:50,2021-09-27 14:01:29,1179,Clinton St & Grand St,5303.06,Madison St & Clinton St,5190.07,40.715595,-73.987030,40.712690,-73.987763,casual
6,B23E6EA33F838C06,classic_bike,2021-09-30 19:52:54,2021-09-30 20:09:38,1004,LaGuardia Pl & W 3 St,5721.14,Madison St & Clinton St,5190.07,40.729170,-73.998102,40.712690,-73.987763,casual
7,96E340E02FD9546E,electric_bike,2021-09-27 17:28:03,2021-09-27 17:43:03,900,E 65 St & 2 Ave,6860.12,5 Ave & E 29 St,6248.06,40.764719,-73.962221,40.745168,-73.986831,member
9,A31C868EABC314D1,classic_bike,2021-09-28 14:23:07,2021-09-28 14:40:46,1059,LaGuardia Pl & W 3 St,5721.14,5 Ave & E 29 St,6248.06,40.729170,-73.998102,40.745168,-73.986831,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280538,1BF6B7F2133A4632,electric_bike,2021-09-27 12:29:14,2021-09-27 12:32:42,208,6 Ave & W 34 St,6364.10,Broadway & W 41 St,6560.01,40.749640,-73.988050,40.755136,-73.986580,casual
3280542,A76F93AB6E0B0EE9,classic_bike,2021-09-28 09:03:14,2021-09-28 09:05:54,160,W 50 St & 9 Ave,6854.05,W 54 St & 11 Ave,6955.05,40.763605,-73.989180,40.768333,-73.992573,member
3280544,F2404E6BA3D5E602,classic_bike,2021-09-29 09:05:10,2021-09-29 09:07:52,162,W 50 St & 9 Ave,6854.05,W 54 St & 11 Ave,6955.05,40.763605,-73.989180,40.768333,-73.992573,member
3280550,D3F560D542122223,classic_bike,2021-09-28 15:10:58,2021-09-28 15:14:01,183,Broadway & W 36 St,6441.01,Broadway & W 41 St,6560.01,40.750977,-73.987654,40.755136,-73.986580,member
3280554,4C929C4486A593B6,classic_bike,2021-09-29 07:13:25,2021-09-29 07:22:42,557,E 2 St & Avenue C,5476.03,Cherry St,5181.04,40.720874,-73.980858,40.712199,-73.979481,member

In [109]:
bike2.to_csv('Resources/202109-citibike.csv',index=False)

In [105]:
bike.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
trip_duration                  int64
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [113]:
station=bike2.groupby('end_station_name').count()
station.sort_values('end_station_id',ascending=False)

,ride_id,rideable_type,started_at,ended_at,trip_duration,start_station_name,start_station_id,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
end_station_name,,,,,,,,,,,,,
W 21 St & 6 Ave,2046,2046,2046,2046,2046,2046,2046,2046,2046,2046,2046,2046,2046
West St & Chambers St,1829,1829,1829,1829,1829,1829,1829,1829,1829,1829,1829,1829,1829
W 20 St & 10 Ave,1824,1824,1824,1824,1824,1824,1824,1824,1824,1824,1824,1824,1824
1 Ave & E 68 St,1748,1748,1748,1748,1748,1748,1748,1748,1748,1748,1748,1748,1748
E 17 St & Broadway,1724,1724,1724,1724,1724,1724,1724,1724,1724,1724,1724,1724,1724
...,...,...,...,...,...,...,...,...,...,...,...,...,...
E 41 St & Madison Ave (SW corner),2,2,2,2,2,2,2,2,2,2,2,2,2
Boerum Pl\t& Pacific St,2,2,2,2,2,2,2,2,2,2,2,2,2
12 St & Sinatra Dr N,1,1,1,1,1,1,1,1,1,1,1,1,1
JC Medical Center,1,1,1,1,1,1,1,1,1,1,1,1,1
Paulus Hook,1,1,1,1,1,1,1,1,1,1,1,1,1